version: "3"
services:

  apache:
    image: docker_lab7_apache
    ports:
      - "3333:80"
    networks:
      - main

  php:
    image: docker_lab7_php
    networks:
        - main
        
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lamp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
        - main

networks:
  main:
